Repository OlegMoiseev/Telezshka, pull requests merged in 2018-10, with the labels that each got.

#9 Fix turn eps
  Telezshka.ino
  TelezshkaLib/AnalogSensor.cpp
  TelezshkaLib/AnalogSensor.h
  TelezshkaLib/AngleMotor.cpp
  TelezshkaLib/AngleMotor.h
  TelezshkaLib/DigitalSensor.cpp
  TelezshkaLib/DigitalSensor.h
  TelezshkaLib/Motor.cpp
  TelezshkaLib/Motor.h
  TelezshkaLib/Odometer.cpp
  TelezshkaLib/Odometer.h
  TelezshkaLib/OptoSensor.cpp
  TelezshkaLib/OptoSensor.h
  TelezshkaLib/Potentiometer.cpp
  TelezshkaLib/Potentiometer.h
  TelezshkaLib/SpeedMotor.cpp
  TelezshkaLib/SpeedMotor.h
  TelezshkaLib/Telezshka.cpp
  TelezshkaLib/Telezshka.h
  TelezshkaLib/Wheel.cpp
  TelezshkaLib/Wheel.h
  TelezshkaLib/defines.h
  telezshka_server/.idea/misc.xml
  telezshka_server/.idea/telezshka.iml
  telezshka_server/.idea/vcs.xml
  telezshka_server/.idea/workspace.xml
  telezshka_server/config.json
Labels: bug, enhancement

#11 Speed motor pid
  Telezshka.ino
  TelezshkaLib/SpeedMotor.cpp
  TelezshkaLib/SpeedMotor.h
  TelezshkaLib/defines.h
Labels: bug

#13 Our interruption work
  Telezshka.ino
  TelezshkaLib/AngleMotor.cpp
  TelezshkaLib/Telezshka.cpp
  Tenzo/Tenzo.ino
Labels: enhancement

#16 Collision processing
  Telezshka.ino
Labels: bug
